version: '3'
services:
  app:
    build: MLT
    links:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "32000:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  python_script:
    build:
      context: MLT
    container_name: python_script
    restart: always
    volumes:
      - .:/app

volumes:
  mysql_data:
