name: Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    env:
      ORG: "sshzink"
      IMAGE_NAME: "mlt"
      TAG: "latest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the docker image
        run: |
          docker build . --file Dockerfile --tag ${ORG}/${IMAGE_NAME}:${TAG}
      - name: Run the tests
        run: |
          docker run -i ${ORG}/${IMAGE_NAME}:${TAG} python -m pytest tests
